version: '3'
services:
  frontend:
    image: frontend:v1
    ports:
      - "3000:3000"  

  backend:
    image: backend:v1
    ports:
      - "4000:4000"  
    depends_on:
      - mongodb 

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"  
    volumes:
      - ./data:/data/db  
