version: "3"
services:
    mongodb:
        image: mongo:latest
        restart: unless-stopped
        env_file: ./server/.env
        ports:
            - "$MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT"
        volumes:
            - ./data:/data/db
    mongo-express:
        image: mongo-express
        restart: unless-stopped
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongodb
            - ME_CONFIG_MONGODB_PORT=27017
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
            - ME_CONFIG_MONGODB_AUTH_DATABASE=le_marrakech
        ports:
            - "8081:8081"
